<?php

class PUMCHItemCodes {
    const LAST_IMPORT = 'LAST_IMPORT';
    const CRM_ID = 'CRM_ID';
    const PATIENT_ID = 'PATIENT_ID';
    const INPATIENT_ID = 'INPATIENT_ID';
    const OPERATION_ID = 'OPERATION_ID';
    const DEPT_CODE = 'DEPARTMENT_CODE';
    const DEPT_NAME = 'INPATIENT_DEPARTMENT';
    const BED_NO = 'BED_NUM';
    const PROCEDURE_TABLE = 'PROC_TABLE';
    const OPERATION_CODE = 'OPERATION_CODE';
    const OPERATION_NAME = 'OPERATION_NAME';
    const OPERATING_ROOM_NO = 'OP_ROOM_NUM';
    const OPERATING_DATETIME = 'OP_TIME';
    const DIAG_BEFORE = 'PREOP_DIAG';
    const EMERGENCY_INDICATOR = 'EMERGENCY_INDICATOR';
    const SURGEON_NAME = 'SURGEON_NAME';
    const SURGEON_CODE = 'SURGEON_CODE';
    const SURGEON_NAME1 = 'ASSIST1_SURGEON_NAME';
    const SURGEON_CODE1 = 'ASSIST1_SURGEON_CODE';
    const ANESTHESIA_DOCTOR_NAME = 'ANESTHESIA_DOC1_NAME';
    const ANESTHESIA_DOCTOR_CODE = 'ANESTHESIA_DOC1_CODE';
    const ANESTHESIA_DOCTOR_NAME2 = 'ANESTHESIA_DOC2_NAME';
    const ANESTHESIA_DOCTOR_CODE2 = 'ANESTHESIA_DOC2_CODE';
    const ANESTHESIA_DOCTOR_NAME3 = 'ANESTHESIA_DOC3_NAME';
    const ANESTHESIA_DOCTOR_CODE3 = 'ANESTHESIA_DOC3_CODE';
    const ANESTHESIA_DOCTOR_NAME4 = 'ANESTHESIA_DOC4_NAME';
    const ANESTHESIA_DOCTOR_CODE4 = 'ANESTHESIA_DOC4_CODE';
    const ANESTHESIA_METHOD = 'ANESTHESIA_METHOD';
    const OPERATION_POSITION = 'SURGICAL_POSITION';
    const NAME = 'PAT_NAME';
    const SEX = 'PAT_GENDER';
    const AGE = 'AGE';
    const BIRTHDAY = 'BIRTHDAY';
    const ID_CARD_TYPE = 'CARD_ID_TYPE';
    const ID_CARD = 'CARD_ID';
    const IN_ROOM_DATETIME = 'INROOM_TIME';
    const OUT_ROOM_DATETIME = 'OUTROOM_TIME';
    const OPER_STATUS = 'OP_STATUS';
    const PHONE = 'PHONE';
    const LAST_UPDATE = 'LAST_UPDATE_TIME';

    //
    const DAY_SURGERY_ADMISSION = 'DAY_SURGERY_ADMISSION';
}

